#!/bin/sh
# EECS2031 - asg2_unix
# Filename: isearch
# Author: Geller, David
# Email: dgeller@my.yorku.ca
# Login ID: dgeller

echo -n "Enter the file name: "
read fname

if test ! -f $fname
then 
echo "File '$fname' does not exist."
exit 1

elif test ! -r $fname
then 
echo "File '$fname' is not readable."
exit 1
fi

echo -n "Enter the word to search for: "
read word

echo -n "Case sensitive (y/n)? "
read sense

while  test $sense != Y && test $sense != y && test $sense != N && test $sense != n
do
echo "Invalid option"
echo -n "Case sensitive (y/n)? "
read sense
done

if test $sense = "y" || test $sense = "Y"
then grep $word $fname

elif test $sense = "n" || test $sense = "N"
then grep -i $word $fname

fi

if test $? -ne 0
then echo "Word '$word' not found."

fi

