#!/bin/sh
# EECS2031 - asg2_unix
# Filename: prtlines
# Author: Geller, David
# Email: dgeller@my.yorku.ca
# Login ID: dgeller

echo -n "Enter the file name: "
read fname

if test ! -f $fname
then
echo "File '$fname' does not exist."
exit 1

elif test ! -r $fname
then
echo "File '$fname' is not readable."
fi

line=`wc -l < $fname`
echo "File '$fname' has $line lines."

echo -n "From line: "
read start

while test $start -le 0 || test $start -ge $line
do
echo "Invalid line number!"
echo -n "From line: "
read start
done

echo -n "To line: "
read end

while test $end -le $start || test $end -ge $line
do 
echo "Invalid line number!"
echo -n "To line: "
read end
done

count=0
cat $fname | while read part1 part2
do
count=`expr $count + 1`

if test $count -ge $start && test $count -le $end
then
echo "$count: $part1 $part2"
fi
done
